// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byuxjyibqpjhwazekszl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5dXhqeWlicXBqaHdhemVrc3psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTQ4MDAsImV4cCI6MjA2NDc5MDgwMH0.R4rs2r_9K-frNtZt6q9gMSWiXUv8KwIoTBvnF2w8j3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);